### ISSUE TITLE
🎉 React Boilerplate setting

### ISSUE THREAD

**Issue by choi2601** [choi2601/triple-project#1]
## 설명
리액트 보일러플레이트 초기 세팅

## todos
- [ ] webpack 초기 설정
- [ ] babel 초기 설정
- [ ] eslint, prettier, stylelint 초기 설정
